fin_dest:
  nifi: {archname: jpl_cordex_sg1, archtype: zip, target_remote_input_port: null requests,
    target_uri: null, transfer: false}
  s3: {bucket: uncc-vifi-bucket, path: jpl_cordex, transfer: false}
  sftp: {dest_path: /home/nifisftp/stat_analysis, host: vifiuitasks-aws.uncc.edu,
    password: osdjf09efjjsflzjdfjweij09ej0fjdjfa, port: 22, transfer: false, username: nifisftp}
  transfer: false
services:
  ocw_cordex_stg1:
    args: [NAM-44, /data/output/CORDEX/analysis, /data/input/obs4mips, /data/input/CORDEX/NAM-44/*]
    cmd_eng: python
    container_dir: null
    data:
      NAM-44: {container_data_path: /data/input/CORDEX/NAM-44, options: null}
      obs4mips: {container_data_path: /data/input/obs4mips, options: null}
    dependencies:
      files: {cordex1.py: f, nam_out: d}
      fn: null
      ser: null
    envs: null
    image: shambakey1/ocw_cordex
    iterative: {cur_iter: 0, max_rep: 1}
    mnts: ['cordex1.py:/usr/local/climate/RCMES/CORDEX/cordex1.py', 'nam_out:/data/output/CORDEX/analysis:rw']
    nifi:
    - archname: jpl_cordex_sg1
      archtype: zip
      results: null
      target_remote_input_port: null requests
      target_uri: a.b.c.d
      transfer: {condition: all_but_last_iteration}
    - archname: jpl_cordex_sg1
      archtype: zip
      results: [a.out, b.out]
      target_remote_input_port: null requests
      target_uri: e.f.g.h
      transfer: {condition: all_but_last_iteration}
    results: null
    s3:
      bucket: uncc-vifi-bucket
      path: jpl_cordex
      results: [grad.out, nll.out, thetas.out]
      transfer: {condition: last_iteration or stop_iteration}
    script: cordex1.py
    ser_check_thr: 300
    sftp:
      dest_path: /home/nifisftp/stat_analysis
      host: vifiuitasks-aws.uncc.edu
      password: osdjf09efjjsflzjdfjweij09ej0fjdjfa
      port: 22
      results: [grad.out, nll.out, thetas.out]
      transfer: {condition: last_iteration or stop_iteration}
      username: nifisftp
    tasks: 1
    toremove: null
    work_dir: null
  ocw_cordex_stg2:
    args: [/data/output/CORDEX/analysis/config_files.csv]
    cmd_eng: python
    container_dir: null
    data:
      NAM-44: {container_data_path: /data/input/CORDEX/NAM-44, options: null}
      obs4mips: {container_data_path: /data/input/obs4mips, options: null}
    dependencies:
      files: {cordex2.py: f, nam_out: d, nam_out/config_files.csv: f}
      fn: null
      ser: null
    envs: ['t={{.Task.Slot}}', repl=1]
    image: shambakey1/ocw_cordex
    iterative: {cur_iter: 0, max_rep: 1}
    mnts: ['cordex2.py:/usr/local/climate/RCMES/CORDEX/cordex2.py', 'nam_out:/data/output/CORDEX/analysis:rw']
    nam_out:
    - {action: move}
    nifi:
    - archname: jpl_cordex_sg1
      archtype: zip
      results: f.out
      target_remote_input_port: null requests
      target_uri: a.b.c.d
      transfer: {condition: never}
    - archname: jpl_cordex_sg1
      archtype: zip
      results: [a.out, b.out]
      target_remote_input_port: null requests
      target_uri: e.f.g.h
      transfer: {condition: all_but_last_iteration}
    results: null
    s3:
      bucket: uncc-vifi-bucket
      path: jpl_cordex
      results: null
      transfer: {condition: last_iteration or stop_iteration}
    script: cordex2.py
    ser_check_thr: 3600
    sftp:
      dest_path: /home/nifisftp/stat_analysis
      host: vifiuitasks-aws.uncc.edu
      password: osdjf09efjjsflzjdfjweij09ej0fjdjfa
      port: 22
      results: [grad.out, nll.out, thetas.out]
      transfer: {condition: last_iteration or stop_iteration}
      username: nifisftp
    stop.iterating:
    - {action: copy}
    tasks: 1
    toremove: null
    work_dir: null
userid: jpl_cordex_sg1
